### ISSUE TITLE
Duplicate data rows from GH obs?

### ISSUE THREAD

**Issue by lydiaPenglish** [vanichols/PFIweeds2020#1]
Not trying to raise any alarms here, but I'm still trying to make sure I understand the data and I ended up running `janitor::get_dupes(pfi_ghobsraw)` and it looks like there are 119 rows that are duplicates. I went back to the raw data sheets to investigate and it looks like some of the duplicates are due to the exact same number/identity of weeds being recorded in two different trays within the same rep. No problem there. But there are other observations that I don't think should be duplicates. For instance on 2019-05-03 in B44_1, there are 39 AMATU and 10 CHEAL recorded twice, but I only see that once on the raw data sheet? 

In fact, I sort of think all of the observations on 2019-05-03 are duplicated. There should only be 45 given the raw data sheet but there are 90 in the dataframe? Not sure if I'm missing something, but it might be good to make sure there isn't a bug somewhere when you read in the data.  

My opinion - I think you should keep "tray" as a variable in `pfi_ghobsraw` - that way each entry for each date is completely unique.

**Comment by vanichols** [comment]
Great catch! 20190503 obs were listed in a stand-alone file AND in the 20190507 file, so they were appearing twice. I changed the  20190503 name so it is no longer being compiled.
